"""add dog breeds

Revision ID: 0724fd75d11b
Revises: 7602cc303d09
Create Date: 2026-07-06 17:42:06.040999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0724fd75d11b'
down_revision: Union[str, Sequence[str], None] = '7602cc303d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_breeds',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('heart_rate_min', sa.Integer(), nullable=False),
    sa.Column('heart_rate_max', sa.Integer(), nullable=False),
    sa.Column('temperature_min', sa.Float(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dog_breeds')),
    schema='dogs'
    )
    op.create_index(op.f('ix_dog_breeds_name'), 'dog_breeds', ['name'], unique=True, schema='dogs')
    op.add_column('dogs', sa.Column('breed_id', sa.UUID(), nullable=True), schema='dogs')
    op.create_index(op.f('ix_dogs_breed_id'), 'dogs', ['breed_id'], unique=False, schema='dogs')
    op.create_foreign_key(op.f('fk_dogs_breed_id_dog_breeds'), 'dogs', 'dog_breeds', ['breed_id'], ['id'], source_schema='dogs', referent_schema='dogs', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_dogs_breed_id_dog_breeds'), 'dogs', schema='dogs', type_='foreignkey')
    op.drop_index(op.f('ix_dogs_breed_id'), table_name='dogs', schema='dogs')
    op.drop_column('dogs', 'breed_id', schema='dogs')
    op.drop_index(op.f('ix_dog_breeds_name'), table_name='dog_breeds', schema='dogs')
    op.drop_table('dog_breeds', schema='dogs')
    # ### end Alembic commands ###
