"""add user phone and type

Revision ID: 23d807d1d7a7
Revises: 0724fd75d11b
Create Date: 2026-07-07 09:43:31.218561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d807d1d7a7'
down_revision: Union[str, Sequence[str], None] = '0724fd75d11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('phone', sa.String(length=30), nullable=True), schema='app')
    op.add_column('app_users', sa.Column('user_type', sa.String(length=30), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'user_type', schema='app')
    op.drop_column('app_users', 'phone', schema='app')
    # ### end Alembic commands ###
