"""improve auth accounts

Revision ID: 7602cc303d09
Revises: f4a4a824819d
Create Date: 2026-07-06 12:08:11.116741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7602cc303d09'
down_revision: Union[str, Sequence[str], None] = 'f4a4a824819d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth_accounts', sa.Column('email', sa.String(length=255), nullable=True), schema='auth')
    op.add_column('user_auth_accounts', sa.Column('is_verified', sa.Boolean(), nullable=False), schema='auth')
    op.add_column('user_auth_accounts', sa.Column('is_active', sa.Boolean(), nullable=False), schema='auth')
    op.create_index(op.f('ix_user_auth_accounts_email'), 'user_auth_accounts', ['email'], unique=False, schema='auth')
    op.create_unique_constraint('uq_auth_provider_email', 'user_auth_accounts', ['provider', 'email'], schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_auth_provider_email', 'user_auth_accounts', schema='auth', type_='unique')
    op.drop_index(op.f('ix_user_auth_accounts_email'), table_name='user_auth_accounts', schema='auth')
    op.drop_column('user_auth_accounts', 'is_active', schema='auth')
    op.drop_column('user_auth_accounts', 'is_verified', schema='auth')
    op.drop_column('user_auth_accounts', 'email', schema='auth')
    # ### end Alembic commands ###
