"""create initial tables

Revision ID: f4a4a824819d
Revises: 
Create Date: 2026-07-06 11:48:13.223191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a4a824819d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users')),
    schema='admin'
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True, schema='admin')
    op.create_table('app_users',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_users')),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True, schema='app')
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('apn', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    schema='devices'
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True, schema='devices')
    op.create_table('user_auth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.app_users.id'], name=op.f('fk_user_auth_accounts_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_auth_accounts')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_provider_user'),
    schema='auth'
    )
    op.create_index(op.f('ix_user_auth_accounts_user_id'), 'user_auth_accounts', ['user_id'], unique=False, schema='auth')
    op.create_table('device_readings',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('internet_connected', sa.Boolean(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('apn', sa.String(length=150), nullable=True),
    sa.Column('dog_temperature', sa.Float(), nullable=True),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.Column('pulse_raw', sa.Integer(), nullable=True),
    sa.Column('heart_bpm', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.devices.id'], name=op.f('fk_device_readings_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_readings')),
    schema='devices'
    )
    op.create_index(op.f('ix_device_readings_device_id'), 'device_readings', ['device_id'], unique=False, schema='devices')
    op.create_table('dogs',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app.app_users.id'], name=op.f('fk_dogs_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dogs')),
    schema='dogs'
    )
    op.create_index(op.f('ix_dogs_owner_id'), 'dogs', ['owner_id'], unique=False, schema='dogs')
    op.create_table('dog_devices',
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.devices.id'], name=op.f('fk_dog_devices_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.dogs.id'], name=op.f('fk_dog_devices_dog_id_dogs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dog_devices')),
    schema='dogs'
    )
    op.create_index(op.f('ix_dog_devices_device_id'), 'dog_devices', ['device_id'], unique=False, schema='dogs')
    op.create_index(op.f('ix_dog_devices_dog_id'), 'dog_devices', ['dog_id'], unique=False, schema='dogs')
    op.create_index('uq_active_device_per_dog', 'dog_devices', ['dog_id'], unique=True, schema='dogs', postgresql_where=sa.text('is_active = true'))
    op.create_index('uq_active_dog_per_device', 'dog_devices', ['device_id'], unique=True, schema='dogs', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_dog_per_device', table_name='dog_devices', schema='dogs', postgresql_where=sa.text('is_active = true'))
    op.drop_index('uq_active_device_per_dog', table_name='dog_devices', schema='dogs', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_dog_devices_dog_id'), table_name='dog_devices', schema='dogs')
    op.drop_index(op.f('ix_dog_devices_device_id'), table_name='dog_devices', schema='dogs')
    op.drop_table('dog_devices', schema='dogs')
    op.drop_index(op.f('ix_dogs_owner_id'), table_name='dogs', schema='dogs')
    op.drop_table('dogs', schema='dogs')
    op.drop_index(op.f('ix_device_readings_device_id'), table_name='device_readings', schema='devices')
    op.drop_table('device_readings', schema='devices')
    op.drop_index(op.f('ix_user_auth_accounts_user_id'), table_name='user_auth_accounts', schema='auth')
    op.drop_table('user_auth_accounts', schema='auth')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices', schema='devices')
    op.drop_table('devices', schema='devices')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users', schema='app')
    op.drop_table('app_users', schema='app')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users', schema='admin')
    op.drop_table('staff_users', schema='admin')
    # ### end Alembic commands ###
